spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/shared_mobility?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    show-sql: true